print("Welcome to Band Name Generator !")
city_name=input("In which city did you grow up ?\n")
pet_name=input("What is the name of your pet?\n")
result=(city_name+" "+pet_name)
print("Name for your band can be : "+result)
